import { AreaChart, Wifi, KeyRound, Database, BarChart, ServerCog, RadioTower, BookUser } from "lucide-react"
import type {
  User,
  Service,
  AuditLog,
  ComplianceStandard,
  AccessMatrixEntry,
  DataOperationLog,
  VpnUser,
  VpnGroup,
  LdapConfiguration,
} from "./types"

export const departments = [
  "Secretariat",
  "Corporate & Social Responsibility Unit",
  "Cybersecurity",
  "eServices",
  "Infrastructure-Data Communication",
  "Cloud Service",
  "Data Centre",
  "Hinterland & Remote Connectivity",
  "Power & Environment",
  "Operations",
  "Project Management Unit",
  "Finance & Admin. Services",
  "Accounts",
  "Procurement",
  "Human Resources",
  "Temporary Staff",
  "LTE Grafana Unit",
  "eSight-SRV-2 Operations",
]

export const users: User[] = [
  {
    id: "1",
    name: "John Smith",
    avatar: "/placeholder.svg?width=40&height=40",
    employeeId: "EMP-2022-0123",
    position: "Cybersecurity Manager",
    department: "Cybersecurity",
    securityClearance: "Top Secret",
    employmentType: "Permanent",
    status: "active",
    lastLogin: "2025-06-28T10:00:00Z",
    vpnAccess: true,
    biometricAccess: true,
    serviceCount: 5,
    email: "john.smith@example.com",
    authenticationType: "LDAP",
    ldapDN: "CN=John Smith,OU=Cybersecurity,DC=company,DC=com",
    adGroups: ["Domain Admins", "Cybersecurity Team", "VPN Users"],
    serviceGroups: [
      {
        serviceName: "Teleport",
        groups: ["Administrators", "Security Team"],
        roles: ["Admin", "Auditor"],
        assignedDate: "2024-01-15",
      },
      {
        serviceName: "Zabbix",
        groups: ["Super Admins", "Security Monitoring"],
        roles: ["Super Admin"],
        assignedDate: "2024-01-15",
      },
    ],
  },
  {
    id: "2",
    name: "Sarah Ahmed",
    avatar: "/placeholder.svg?width=40&height=40",
    employeeId: "EMP-2021-4567",
    position: "Network Engineer",
    department: "Infrastructure-Data Communication",
    securityClearance: "Confidential",
    employmentType: "Permanent",
    status: "active",
    lastLogin: "2025-06-29T08:30:00Z",
    vpnAccess: true,
    biometricAccess: false,
    serviceCount: 8,
    email: "sarah.ahmed@example.com",
    authenticationType: "LDAP",
    ldapDN: "CN=Sarah Ahmed,OU=Infrastructure,DC=company,DC=com",
    adGroups: ["Network Engineers", "Infrastructure Team", "VPN Users"],
    serviceGroups: [
      {
        serviceName: "IPAM",
        groups: ["Network Administrators", "IP Managers"],
        roles: ["Network Admin", "Subnet Manager"],
        assignedDate: "2024-02-01",
      },
      {
        serviceName: "Unifi",
        groups: ["Network Controllers", "WiFi Managers"],
        roles: ["Admin", "Hotspot Manager"],
        assignedDate: "2024-02-01",
      },
    ],
  },
  {
    id: "3",
    name: "Michael Chen",
    avatar: "/placeholder.svg?width=40&height=40",
    employeeId: "EMP-2023-8901",
    position: "LTE Engineer",
    department: "LTE Grafana Unit",
    securityClearance: "Internal",
    employmentType: "Permanent",
    status: "active",
    lastLogin: "2025-06-29T11:15:00Z",
    vpnAccess: true,
    biometricAccess: true,
    serviceCount: 3,
    email: "michael.chen@example.com",
    authenticationType: "Local",
    localGroups: ["LTE Engineers", "Monitoring Users"],
    serviceGroups: [
      {
        serviceName: "Grafana",
        groups: ["LTE Monitoring", "Dashboard Editors"],
        roles: ["Editor", "Viewer"],
        assignedDate: "2024-03-01",
      },
    ],
  },
  {
    id: "4",
    name: "Fatima Al-Zahra",
    avatar: "/placeholder.svg?width=40&height=40",
    employeeId: "EMP-2020-2345",
    position: "Finance Officer",
    department: "Finance & Admin. Services",
    securityClearance: "Internal",
    employmentType: "Permanent",
    status: "active",
    lastLogin: "2025-06-29T09:05:00Z",
    vpnAccess: false,
    biometricAccess: false,
    serviceCount: 2,
    email: "fatima.alzahra@example.com",
    authenticationType: "Azure AD",
    adGroups: ["Finance Team", "Office 365 Users"],
    serviceGroups: [
      {
        serviceName: "ITop",
        groups: ["Finance Users", "Service Requesters"],
        roles: ["Agent"],
        assignedDate: "2024-01-10",
      },
    ],
  },
  {
    id: "5",
    name: "David Garcia",
    avatar: "/placeholder.svg?width=40&height=40",
    employeeId: "EMP-2024-6789",
    position: "Data Centre Operator",
    department: "Data Centre",
    securityClearance: "Restricted",
    employmentType: "Contract",
    status: "inactive",
    lastLogin: "2025-05-15T14:00:00Z",
    vpnAccess: true,
    biometricAccess: true,
    serviceCount: 6,
    email: "david.garcia@example.com",
    authenticationType: "Local",
    localGroups: ["Data Centre Operators", "Infrastructure Users"],
    serviceGroups: [
      {
        serviceName: "eSight-SRV-2",
        groups: ["Server Operators", "Hardware Monitoring"],
        roles: ["Operator"],
        assignedDate: "2024-04-01",
        expiresOn: "2025-12-31",
      },
    ],
  },
  {
    id: "6",
    name: "Aisha Khan",
    avatar: "/placeholder.svg?width=40&height=40",
    employeeId: "EMP-2025-TEMP",
    position: "Consultant",
    department: "Temporary Staff",
    securityClearance: "Public",
    employmentType: "Temporary",
    status: "active",
    lastLogin: "2025-06-29T14:00:00Z",
    vpnAccess: true,
    biometricAccess: false,
    serviceCount: 1,
    email: "aisha.khan@contractor.example.com",
    expiresOn: "2025-09-30T23:59:59Z",
    authenticationType: "Local",
    localGroups: ["Contractors", "Temporary Users"],
    serviceGroups: [
      {
        serviceName: "Unifi",
        groups: ["Guest Users", "Limited Access"],
        roles: ["Limited Admin"],
        assignedDate: "2025-06-01",
        expiresOn: "2025-09-30",
      },
    ],
  },
]

export const services: Service[] = [
  {
    name: "IPAM",
    icon: Database,
    description: "IP Address Management",
    category: "Network",
    activeUsers: 150,
    health: "Operational",
    roles: ["Network Admin", "Subnet Manager", "IP Viewer", "DHCP Manager"],
    authenticationMethods: ["LDAP", "Local"],
    ldapIntegration: true,
    customGroups: [
      {
        id: "ipam-1",
        name: "Network Administrators",
        description: "Full network management access",
        permissions: ["create_subnets", "manage_dhcp", "view_all_networks"],
        members: ["2"],
        createdDate: "2024-01-01",
        isDefault: true,
      },
      {
        id: "ipam-2",
        name: "IP Managers",
        description: "IP allocation and management",
        permissions: ["allocate_ips", "view_subnets"],
        members: ["2"],
        createdDate: "2024-01-01",
        isDefault: false,
      },
    ],
  },
  {
    name: "Unifi",
    icon: Wifi,
    description: "Network Controller",
    category: "Network",
    activeUsers: 800,
    health: "Operational",
    roles: ["Super Admin", "Admin", "Hotspot Manager", "Limited Admin"],
    authenticationMethods: ["LDAP", "Local", "SAML SSO"],
    ldapIntegration: true,
    customGroups: [
      {
        id: "unifi-1",
        name: "Network Controllers",
        description: "Full UniFi controller access",
        permissions: ["manage_devices", "configure_networks", "view_statistics"],
        members: ["2"],
        createdDate: "2024-01-01",
        isDefault: true,
      },
      {
        id: "unifi-2",
        name: "WiFi Managers",
        description: "WiFi network management",
        permissions: ["manage_wifi", "view_clients"],
        members: ["2"],
        createdDate: "2024-01-01",
        isDefault: false,
      },
      {
        id: "unifi-3",
        name: "Guest Users",
        description: "Limited access for temporary users",
        permissions: ["view_basic_stats"],
        members: ["6"],
        createdDate: "2024-01-01",
        isDefault: false,
      },
    ],
  },
  {
    name: "NOC",
    icon: RadioTower,
    description: "Network Operations Center",
    category: "Monitoring",
    activeUsers: 50,
    health: "Degraded",
    roles: ["NOC Engineer", "Senior NOC", "NOC Manager", "Observer"],
    authenticationMethods: ["LDAP", "Local"],
    ldapIntegration: true,
    customGroups: [
      {
        id: "noc-1",
        name: "NOC Engineers",
        description: "Network monitoring and incident response",
        permissions: ["view_alerts", "acknowledge_incidents", "create_tickets"],
        members: [],
        createdDate: "2024-01-01",
        isDefault: true,
      },
    ],
  },
  {
    name: "Grafana",
    icon: AreaChart,
    description: "General Monitoring",
    category: "Monitoring",
    activeUsers: 450,
    health: "Operational",
    roles: ["Admin", "Editor", "Viewer", "Data Source Admin"],
    authenticationMethods: ["LDAP", "Local", "Azure AD"],
    ldapIntegration: true,
    customGroups: [
      {
        id: "grafana-1",
        name: "LTE Monitoring",
        description: "LTE network monitoring dashboards",
        permissions: ["view_lte_dashboards", "edit_lte_panels"],
        members: ["3"],
        createdDate: "2024-01-01",
        isDefault: false,
      },
      {
        id: "grafana-2",
        name: "Dashboard Editors",
        description: "Dashboard creation and editing",
        permissions: ["create_dashboards", "edit_dashboards", "manage_folders"],
        members: ["3"],
        createdDate: "2024-01-01",
        isDefault: true,
      },
    ],
  },
  {
    name: "Zabbix",
    icon: BarChart,
    description: "Infrastructure Monitoring",
    category: "Monitoring",
    activeUsers: 200,
    health: "Operational",
    roles: ["Super Admin", "Admin", "User", "Guest"],
    authenticationMethods: ["LDAP", "Local"],
    ldapIntegration: true,
    customGroups: [
      {
        id: "zabbix-1",
        name: "Super Admins",
        description: "Full Zabbix administration",
        permissions: ["full_access"],
        members: ["1"],
        createdDate: "2024-01-01",
        isDefault: true,
      },
      {
        id: "zabbix-2",
        name: "Security Monitoring",
        description: "Security-focused monitoring",
        permissions: ["view_security_hosts", "manage_security_triggers"],
        members: ["1"],
        createdDate: "2024-01-01",
        isDefault: false,
      },
    ],
  },
  {
    name: "Teleport",
    icon: KeyRound,
    description: "Secure Access",
    category: "Security",
    activeUsers: 120,
    health: "Operational",
    roles: ["Admin", "Access", "Auditor", "Requester"],
    authenticationMethods: ["LDAP", "SAML SSO"],
    ldapIntegration: true,
    customGroups: [
      {
        id: "teleport-1",
        name: "Administrators",
        description: "Teleport cluster administration",
        permissions: ["manage_cluster", "manage_users", "view_audit_logs"],
        members: ["1"],
        createdDate: "2024-01-01",
        isDefault: true,
      },
      {
        id: "teleport-2",
        name: "Security Team",
        description: "Security-focused access management",
        permissions: ["manage_roles", "view_sessions", "audit_access"],
        members: ["1"],
        createdDate: "2024-01-01",
        isDefault: false,
      },
    ],
  },
  {
    name: "eSight-SRV-2",
    icon: ServerCog,
    description: "Server Management",
    category: "Management",
    activeUsers: 75,
    health: "Operational",
    roles: ["Server Admin", "System Engineer", "Operator"],
    authenticationMethods: ["Local", "LDAP"],
    ldapIntegration: true,
    customGroups: [
      {
        id: "esight-1",
        name: "Server Operators",
        description: "Server monitoring and basic operations",
        permissions: ["view_servers", "basic_operations"],
        members: ["5"],
        createdDate: "2024-01-01",
        isDefault: true,
      },
      {
        id: "esight-2",
        name: "Hardware Monitoring",
        description: "Hardware health monitoring",
        permissions: ["view_hardware_status", "generate_reports"],
        members: ["5"],
        createdDate: "2024-01-01",
        isDefault: false,
      },
    ],
  },
  {
    name: "ITop",
    icon: BookUser,
    description: "IT Service Management",
    category: "Management",
    activeUsers: 950,
    health: "Operational",
    roles: ["Administrator", "Service Manager", "Agent"],
    authenticationMethods: ["LDAP", "Local", "Azure AD"],
    ldapIntegration: true,
    customGroups: [
      {
        id: "itop-1",
        name: "Finance Users",
        description: "Finance department service requests",
        permissions: ["create_requests", "view_own_tickets"],
        members: ["4"],
        createdDate: "2024-01-01",
        isDefault: false,
      },
      {
        id: "itop-2",
        name: "Service Requesters",
        description: "General service request access",
        permissions: ["create_requests", "view_catalog"],
        members: ["4"],
        createdDate: "2024-01-01",
        isDefault: true,
      },
    ],
  },
]

export const vpnUsers: VpnUser[] = [
  {
    id: "vpn-user-1",
    userId: "1",
    username: "john.smith",
    vpnType: "FortiGate",
    groups: ["Executive_Access", "IT_Staff"],
    ipPool: "172.16.10.0/24",
    allowedNetworks: ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"],
    maxSessions: 3,
    dataLimit: "50GB",
    timeLimit: "24h",
    status: "Active",
    createdDate: "2024-01-15",
    lastConnection: "2025-06-29T10:00:00Z",
    totalDataUsed: "15.2GB",
    authenticationType: "LDAP",
    certificate: "john.smith.p12",
  },
  {
    id: "vpn-user-2",
    userId: "2",
    username: "sarah.ahmed",
    vpnType: "Mikrotik",
    groups: ["Engineers", "Remote_Workers"],
    ipPool: "10.8.0.0/24",
    allowedNetworks: ["10.0.0.0/8", "172.16.0.0/12"],
    maxSessions: 2,
    dataLimit: "20GB",
    timeLimit: "12h",
    status: "Active",
    createdDate: "2024-02-01",
    lastConnection: "2025-06-29T08:30:00Z",
    totalDataUsed: "8.7GB",
    authenticationType: "LDAP",
    sharedSecret: "shared-secret-key",
  },
  {
    id: "vpn-user-3",
    userId: "6",
    username: "aisha.khan",
    vpnType: "Mikrotik",
    groups: ["Contractors", "Temporary_Staff"],
    ipPool: "10.8.100.0/24",
    allowedNetworks: ["192.168.1.0/24"],
    maxSessions: 1,
    dataLimit: "5GB",
    timeLimit: "8h",
    status: "Active",
    createdDate: "2025-06-01",
    lastConnection: "2025-06-29T14:00:00Z",
    totalDataUsed: "2.1GB",
    authenticationType: "Local",
  },
]

export const vpnGroups: VpnGroup[] = [
  {
    id: "vpn-group-1",
    name: "Executive_Access",
    vpnType: "FortiGate",
    description: "High-level executive access with full network privileges",
    ipPool: "172.16.10.0/24",
    allowedNetworks: ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"],
    defaultDataLimit: "100GB",
    defaultTimeLimit: "24h",
    priority: 1,
    members: ["vpn-user-1"],
    policies: [
      {
        id: "policy-1",
        name: "Full Network Access",
        description: "Allow access to all internal networks",
        rules: [
          {
            action: "Allow",
            source: "172.16.10.0/24",
            destination: "10.0.0.0/8",
            protocol: "Any",
          },
        ],
      },
    ],
  },
  {
    id: "vpn-group-2",
    name: "Engineers",
    vpnType: "Mikrotik",
    description: "Engineering team with infrastructure access",
    ipPool: "10.8.0.0/24",
    allowedNetworks: ["10.0.0.0/8", "172.16.0.0/12"],
    defaultDataLimit: "20GB",
    defaultTimeLimit: "12h",
    priority: 2,
    members: ["vpn-user-2"],
    policies: [
      {
        id: "policy-2",
        name: "Infrastructure Access",
        description: "Access to infrastructure networks",
        rules: [
          {
            action: "Allow",
            source: "10.8.0.0/24",
            destination: "10.0.0.0/8",
            protocol: "Any",
          },
        ],
      },
    ],
  },
  {
    id: "vpn-group-3",
    name: "Contractors",
    vpnType: "Mikrotik",
    description: "Limited access for external contractors",
    ipPool: "10.8.100.0/24",
    allowedNetworks: ["192.168.1.0/24"],
    defaultDataLimit: "5GB",
    defaultTimeLimit: "8h",
    priority: 5,
    members: ["vpn-user-3"],
    policies: [
      {
        id: "policy-3",
        name: "Limited Access",
        description: "Restricted access to specific networks only",
        rules: [
          {
            action: "Allow",
            source: "10.8.100.0/24",
            destination: "192.168.1.0/24",
            port: "80,443",
            protocol: "TCP",
          },
        ],
      },
    ],
  },
]

export const ldapConfiguration: LdapConfiguration = {
  server: "ldap.company.com",
  port: 389,
  baseDN: "DC=company,DC=com",
  bindDN: "CN=ldap-service,OU=Service Accounts,DC=company,DC=com",
  searchFilter: "(&(objectClass=user)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))",
  userAttributes: {
    username: "sAMAccountName",
    email: "mail",
    firstName: "givenName",
    lastName: "sn",
    department: "department",
    groups: "memberOf",
  },
  groupMapping: {
    "CN=Domain Admins,CN=Users,DC=company,DC=com": ["Administrators", "IT_Staff"],
    "CN=Cybersecurity Team,OU=Security,DC=company,DC=com": ["Security Team", "VPN Users"],
    "CN=Network Engineers,OU=Infrastructure,DC=company,DC=com": ["Engineers", "Network Controllers"],
  },
  syncEnabled: true,
  lastSync: "2025-06-29T06:00:00Z",
}

export const auditLogs: AuditLog[] = [
  {
    id: "log-001",
    user: {
      name: "John Smith",
      avatar: "/placeholder.svg?width=32&height=32",
      authenticationType: "LDAP",
    },
    action: "User Login",
    actionType: "SECURITY",
    timestamp: "2025-06-29T13:01:14Z",
    details: "Successful LDAP authentication from IP 192.168.1.10",
    ipAddress: "192.168.1.10",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
  },
  {
    id: "log-002",
    user: {
      name: "System",
      avatar: "/placeholder.svg?width=32&height=32",
    },
    action: "VPN Group Created",
    actionType: "GROUP_MANAGEMENT",
    timestamp: "2025-06-29T12:45:32Z",
    details: "Created new VPN group 'Contractors' with limited access policies",
  },
  {
    id: "log-003",
    user: {
      name: "Sarah Ahmed",
      avatar: "/placeholder.svg?width=32&height=32",
      authenticationType: "LDAP",
    },
    action: "Service Group Assignment",
    actionType: "GROUP_MANAGEMENT",
    timestamp: "2025-06-29T11:30:00Z",
    details: "Added user 'Aisha Khan' to Unifi 'Guest Users' group with expiration date",
  },
  {
    id: "log-004",
    user: {
      name: "Michael Chen",
      avatar: "/placeholder.svg?width=32&height=32",
      authenticationType: "Local",
    },
    action: "LDAP Sync Completed",
    actionType: "SYSTEM",
    timestamp: "2025-06-29T06:00:00Z",
    details: "LDAP synchronization completed successfully. 15 users updated, 3 new groups mapped",
  },
]

export const accessMatrixData: AccessMatrixEntry[] = [
  {
    userId: "1",
    serviceName: "Teleport",
    accessLevel: "Full",
    role: "Admin",
    groups: ["Administrators", "Security Team"],
    expiresOn: "2026-01-01",
    grantedBy: "System",
    grantedDate: "2024-01-15",
  },
  {
    userId: "1",
    serviceName: "Grafana",
    accessLevel: "Limited",
    role: "Viewer",
    groups: ["Dashboard Viewers"],
    grantedBy: "Admin",
    grantedDate: "2024-01-15",
  },
  {
    userId: "1",
    serviceName: "Zabbix",
    accessLevel: "Full",
    role: "Super Admin",
    groups: ["Super Admins", "Security Monitoring"],
    grantedBy: "System",
    grantedDate: "2024-01-15",
  },
  {
    userId: "2",
    serviceName: "IPAM",
    accessLevel: "Full",
    role: "Network Admin",
    groups: ["Network Administrators", "IP Managers"],
    grantedBy: "John Smith",
    grantedDate: "2024-02-01",
  },
  {
    userId: "2",
    serviceName: "Unifi",
    accessLevel: "Full",
    role: "Admin",
    groups: ["Network Controllers", "WiFi Managers"],
    grantedBy: "John Smith",
    grantedDate: "2024-02-01",
  },
  {
    userId: "6",
    serviceName: "Unifi",
    accessLevel: "Limited",
    role: "Limited Admin",
    groups: ["Guest Users"],
    expiresOn: "2025-09-30",
    grantedBy: "Sarah Ahmed",
    grantedDate: "2025-06-01",
  },
]

// Legacy exports for backward compatibility
export const mikrotikVpnGroups = vpnGroups.filter((g) => g.vpnType === "Mikrotik").map((g) => g.name)
export const fortiGateVpnGroups = vpnGroups.filter((g) => g.vpnType === "FortiGate").map((g) => g.name)

interface VpnConnection {
  id: string
  user: {
    name: string
    avatar: string
  }
  vpnType: "Mikrotik" | "FortiGate"
  group: string
  ipAddress: string
  dataUsage: string
  sessionDuration: string
  status: "Connected"
}

export const activeVpnConnections: VpnConnection[] = [
  {
    id: "vpn1",
    user: { name: "Sarah Ahmed", avatar: "/placeholder.svg?width=40&height=40" },
    vpnType: "Mikrotik",
    group: "Engineers",
    ipAddress: "10.8.0.5",
    dataUsage: "1.2 GB",
    sessionDuration: "3h 45m",
    status: "Connected",
  },
  {
    id: "vpn2",
    user: { name: "John Smith", avatar: "/placeholder.svg?width=40&height=40" },
    vpnType: "FortiGate",
    group: "Executive_Access",
    ipAddress: "172.16.10.22",
    dataUsage: "350 MB",
    sessionDuration: "1h 12m",
    status: "Connected",
  },
  {
    id: "vpn3",
    user: { name: "Aisha Khan", avatar: "/placeholder.svg?width=40&height=40" },
    vpnType: "Mikrotik",
    group: "Contractors",
    ipAddress: "10.8.100.15",
    dataUsage: "870 MB",
    sessionDuration: "6h 02m",
    status: "Connected",
  },
]

export const complianceData: ComplianceStandard[] = [
  {
    name: "SOC 2",
    description:
      "Trust Services Criteria for Security, Availability, Processing Integrity, Confidentiality, and Privacy.",
    controls: [
      {
        id: "SOC2-CC6.1",
        name: "Logical Access Control",
        description: "The entity implements logical access security software, infrastructure, and architectures.",
        status: "Compliant",
        owner: "Cybersecurity",
        lastReviewed: "2025-06-15",
        evidenceCount: 5,
      },
      {
        id: "SOC2-CC7.1",
        name: "Change Management",
        description: "The entity uses a defined change management process.",
        status: "In Progress",
        owner: "Operations",
        lastReviewed: "2025-05-20",
        evidenceCount: 2,
      },
      {
        id: "SOC2-A1.2",
        name: "Risk Assessment",
        description: "The entity conducts risk assessments to identify and analyze risks.",
        status: "Compliant",
        owner: "Cybersecurity",
        lastReviewed: "2025-06-01",
        evidenceCount: 8,
      },
    ],
  },
  {
    name: "GDPR",
    description: "General Data Protection Regulation for data protection and privacy in the European Union.",
    controls: [
      {
        id: "GDPR-Art32",
        name: "Security of Processing",
        description:
          "Implement technical and organizational measures to ensure a level of security appropriate to the risk.",
        status: "Compliant",
        owner: "Cybersecurity",
        lastReviewed: "2025-06-10",
        evidenceCount: 12,
      },
      {
        id: "GDPR-Art30",
        name: "Records of Processing Activities",
        description: "Maintain a record of processing activities under its responsibility.",
        status: "Non-Compliant",
        owner: "eServices",
        lastReviewed: "2025-04-30",
        evidenceCount: 1,
      },
    ],
  },
  {
    name: "ISO 27001",
    description: "International standard for information security management systems (ISMS).",
    controls: [
      {
        id: "ISO-A.9.4.1",
        name: "Information Access Restriction",
        description:
          "Access to information and application system functions shall be restricted in accordance with the access control policy.",
        status: "Compliant",
        owner: "Infrastructure-Data Communication",
        lastReviewed: "2025-06-18",
        evidenceCount: 7,
      },
      {
        id: "ISO-A.12.1.2",
        name: "Protection against Malware",
        description: "Controls to protect against malware shall be implemented and used.",
        status: "Compliant",
        owner: "Cybersecurity",
        lastReviewed: "2025-06-20",
        evidenceCount: 4,
      },
      {
        id: "ISO-A.14.2.1",
        name: "Secure Development Policy",
        description: "Rules for the development of software and systems shall be established and applied.",
        status: "Not Assessed",
        owner: "Project Management Unit",
        lastReviewed: "N/A",
        evidenceCount: 0,
      },
    ],
  },
]

export const dataOperationLogs: DataOperationLog[] = [
  {
    id: "op-001",
    type: "Import",
    dataType: "Users",
    fileName: "new_hires_q2.csv",
    status: "Completed",
    timestamp: "2025-06-28T14:30:00Z",
    recordsProcessed: 15,
    user: { name: "John Smith" },
  },
  {
    id: "op-002",
    type: "Export",
    dataType: "VPN Users",
    fileName: "vpn_users_20250628.csv",
    status: "Completed",
    timestamp: "2025-06-28T10:00:00Z",
    recordsProcessed: 45,
    user: { name: "Sarah Ahmed" },
  },
  {
    id: "op-003",
    type: "Import",
    dataType: "Groups",
    fileName: "service_groups_update.csv",
    status: "Failed",
    timestamp: "2025-06-27T11:00:00Z",
    recordsProcessed: 0,
    user: { name: "Admin" },
  },
  {
    id: "op-004",
    type: "Export",
    dataType: "Services",
    fileName: "active_services.json",
    status: "Completed",
    timestamp: "2025-06-26T16:45:00Z",
    recordsProcessed: 16,
    user: { name: "John Smith" },
  },
]
